// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "Codenameillusion_dialogExpressoScripts.h"
#include "Codenameillusion_dialogDatabase.generated.h"

UCLASS(BlueprintType)
class CODENAMEILLUSION_API UCodenameillusion_dialogDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UCodenameillusion_dialogDatabase() 
	{
		SetExpressoScriptsClass(UCodenameillusion_dialogExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UCodenameillusion_dialogDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UCodenameillusion_dialogDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UCodenameillusion_dialogGlobalVariables* GetGVs() const override
	{
		return static_cast<UCodenameillusion_dialogGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UCodenameillusion_dialogGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UCodenameillusion_dialogGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
