// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyLocalizerSystem.h"
#include "Codenameillusion_dialogLocalizerSystem.generated.h"

/** Articy Localizer System */
UCLASS(BlueprintType)
class CODENAMEILLUSION_API UCodenameillusion_dialogLocalizerSystem : public UArticyLocalizerSystem
{
	GENERATED_BODY()
	
public:
	void Reload() 
	{
		const FString& LangName = FInternationalization::Get().GetCurrentCulture()->GetTwoLetterISOLanguageName();
		if (!bListenerSet) {
			FInternationalization::Get().OnCultureChanged().AddUObject(this, &UCodenameillusion_dialogLocalizerSystem::Reload);
			bListenerSet = true;
		}
FStringTableRegistry::Get().UnregisterStringTable(FName("All_objects"));
LOCTABLE_FROMFILE_GAME("All_objects", "All_objects", "ArticyContent/Generated/All_objects.csv");
		if (LangName.Equals("en")) {
			FStringTableRegistry::Get().UnregisterStringTable(FName("All_objects"));
			LOCTABLE_FROMFILE_GAME("All_objects", "All_objects", "L10N/en/ArticyContent/Generated/All_objects.csv");
		}
		bDataLoaded = true;
	}
};
