// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "Codenameillusion_dialogInterfaces.generated.h"


/** UNINTERFACE generated from Articy Basic Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Codenameillusion_dialog Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UCodenameillusion_dialogObjectWithDefaultBasicCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class ICodenameillusion_dialogObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UCodenameillusion_dialogDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Extended Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Codenameillusion_dialog Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UCodenameillusion_dialogObjectWithDefaultExtendedCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class ICodenameillusion_dialogObjectWithDefaultExtendedCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UCodenameillusion_dialogDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};
