// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyTypeSystem.h"
#include "Codenameillusion_dialogTypeSystem.generated.h"

/** Articy Type System */
UCLASS(BlueprintType)
class CODENAMEILLUSION_API UCodenameillusion_dialogTypeSystem : public UArticyTypeSystem
{
	GENERATED_BODY()
	
};
